/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;

/**
 *
 * @author Pranav
 */
public class FrmPoolCreate extends javax.swing.JFrame {

    static int id=0;
   public void setId()
        {
        id++;     
        }
    
   public int getUniqueId()
        {
        return id;
        }
    
    /**
     * Creates new form FrmCreate
     */
    public FrmPoolCreate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCar = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtCar = new javax.swing.JTextField();
        jspSeats = new javax.swing.JSpinner();
        lblDate = new javax.swing.JLabel();
        jDate = new org.jdesktop.swingx.JXDatePicker();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblStreet = new javax.swing.JLabel();
        cbxRegion = new javax.swing.JComboBox();
        cbxStreet = new javax.swing.JComboBox();
        lblRegion = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        cbxCity = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        lblStreet1 = new javax.swing.JLabel();
        cbxRegion1 = new javax.swing.JComboBox();
        cbxStreet1 = new javax.swing.JComboBox();
        lblRegion1 = new javax.swing.JLabel();
        lblCity1 = new javax.swing.JLabel();
        cbxCity1 = new javax.swing.JComboBox();
        btnClear = new javax.swing.JButton();
        jTime = new lu.tudor.santec.jtimechooser.JTimeChooser();
        lblUnique = new javax.swing.JLabel();
        txtUnique = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pooling");

        lblCar.setText("Car:");

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        lblTime.setText("Time:");

        lblSeats.setText("Seats:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jspSeats.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));

        lblDate.setText("Date:");

        jDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDateFocusLost(evt);
            }
        });
        jDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "From"));

        lblStreet.setText("Street:");

        cbxRegion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxRegionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxRegionFocusLost(evt);
            }
        });
        cbxRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRegionActionPerformed(evt);
            }
        });

        cbxStreet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxStreetFocusGained(evt);
            }
        });

        lblRegion.setText("Region:");

        lblCity.setText("City:");

        cbxCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pune" }));
        cbxCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxCityFocusLost(evt);
            }
        });
        cbxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblRegion)
                        .addComponent(lblStreet))
                    .addComponent(lblCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCity, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxCity, cbxRegion, cbxStreet});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCity, lblRegion, lblStreet});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(cbxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion)
                    .addComponent(cbxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet)
                    .addComponent(cbxStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxCity, cbxRegion, cbxStreet, lblCity, lblRegion, lblStreet});

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "To"));

        lblStreet1.setText("Street:");

        cbxRegion1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxRegion1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxRegion1FocusLost(evt);
            }
        });
        cbxRegion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRegion1ActionPerformed(evt);
            }
        });

        cbxStreet1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxStreet1FocusGained(evt);
            }
        });

        lblRegion1.setText("Region:");

        lblCity1.setText("City:");

        cbxCity1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pune" }));
        cbxCity1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxCity1FocusLost(evt);
            }
        });
        cbxCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCity1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblRegion1)
                        .addComponent(lblStreet1))
                    .addComponent(lblCity1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxStreet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxRegion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxCity1, cbxRegion1, cbxStreet1});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCity1, lblRegion1, lblStreet1});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity1)
                    .addComponent(cbxCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion1)
                    .addComponent(cbxRegion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet1)
                    .addComponent(cbxStreet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxCity1, cbxRegion1, cbxStreet1, lblCity1, lblRegion1, lblStreet1});

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblUnique.setText("Unique Ride Name:");

        lblTitle.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblTitle.setText("Create Car Pooling");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCar)
                                    .addComponent(lblDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTime)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSeats)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jspSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUnique)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUnique, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnSubmit)
                        .addGap(15, 15, 15)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCar, lblDate, lblUnique});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblSeats, lblTime});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnClear, btnHome, btnSubmit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSeats)
                                .addComponent(jspSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblTime))
                        .addComponent(jTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCar)
                            .addComponent(txtCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDate)
                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnique)
                    .addComponent(txtUnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnClear)
                    .addComponent(btnBack)
                    .addComponent(btnHome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jDate, jTime, jspSeats, lblCar, lblDate, lblSeats, lblTime, lblUnique, txtCar, txtUnique});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FrmPoolCar frc=new FrmPoolCar();
        frc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateFocusLost
        //String date=jdpDate.getDate().toString();
    }//GEN-LAST:event_jDateFocusLost

    private void jtcTimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtcTimeFocusLost
       // String time=jtcTime.getFormatedTime();
    }//GEN-LAST:event_jtcTimeFocusLost

    private void jDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateActionPerformed

    private void cbxRegionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxRegionFocusGained

    }//GEN-LAST:event_cbxRegionFocusGained

    private void cbxRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRegionActionPerformed

    private void cbxStreetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxStreetFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxStreetFocusGained

    private void cbxRegionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxRegionFocusLost
        String selected=cbxRegion.getSelectedItem().toString();
     Connect c1=new Connect();
    DBCollection dbc=c1.connectStreet(selected);
    BasicDBObject bdb=new BasicDBObject();
    int i=0;
    DBCursor cursor=dbc.find();
    
    cbxStreet.removeAllItems();
    
    
    while(cursor.hasNext())
    {
        DBObject obj=cursor.next();
        String street=obj.get("name").toString();
        cbxStreet.addItem(street);
        
    }
    }//GEN-LAST:event_cbxRegionFocusLost

    private void cbxCityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxCityFocusLost
        // TODO add your handling code here:

        Connect c1=new Connect();
        DBCollection dbc=c1.connectRegion();
        BasicDBObject bdb=new BasicDBObject();
        int i=0;
        DBCursor cursor=dbc.find();

        while(cursor.hasNext())
        {
            DBObject obj=cursor.next();
            String region=obj.get("name").toString();
            cbxRegion.addItem(region);

        }

    }//GEN-LAST:event_cbxCityFocusLost

    private void cbxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCityActionPerformed

    private void cbxRegion1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxRegion1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRegion1FocusGained

    private void cbxRegion1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxRegion1FocusLost
  String selected=cbxRegion1.getSelectedItem().toString();
    Connect c1=new Connect();
    DBCollection dbc=c1.connectStreet(selected);
    BasicDBObject bdb=new BasicDBObject();
    int i=0;
    DBCursor cursor=dbc.find();
 cbxStreet1.removeAllItems();
    while(cursor.hasNext())
    {
        DBObject obj=cursor.next();
        String street=obj.get("name").toString();
        cbxStreet1.addItem(street);
        
    }
    }//GEN-LAST:event_cbxRegion1FocusLost

    private void cbxRegion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRegion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRegion1ActionPerformed

    private void cbxStreet1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxStreet1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxStreet1FocusGained

    private void cbxCity1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxCity1FocusLost
        
              
    Connect c1=new Connect();
    DBCollection dbc=c1.connectRegion();
    BasicDBObject bdb=new BasicDBObject();
    int i=0;
    DBCursor cursor=dbc.find();
    
    while(cursor.hasNext())
    {
        DBObject obj=cursor.next();
        String region=obj.get("name").toString();
        cbxRegion1.addItem(region);
        
    }// TODO add your handling code here:
    }//GEN-LAST:event_cbxCity1FocusLost

    private void cbxCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCity1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
      
        FrmWelcome f3 = new FrmWelcome();
       
        this.setId();
        String no = ""+getUniqueId();
        no.trim();
        String fcity=cbxCity.getSelectedItem().toString();
        String fregion=cbxRegion.getSelectedItem().toString();
        String fstreet=cbxStreet.getSelectedItem().toString();
        String tcity=cbxCity1.getSelectedItem().toString();
        String tregion=cbxRegion1.getSelectedItem().toString();
        String tstreet=cbxStreet1.getSelectedItem().toString();    
        String car=txtCar.getText();
        String seats=jspSeats.getValue().toString();
        String curUser = f3.getUser();
        String unique=txtUnique.getText();
        Connect c1=new Connect();
        DBCollection dbc=c1.connectPool();
        BasicDBObject bdb=new BasicDBObject();
        bdb.put("fcity",fcity);
        bdb.put("fregion",fregion);
        bdb.put("fstreet",fstreet);
        bdb.put("tcity",tcity);
        bdb.put("tregion",tregion);
        bdb.put("tstreet",tstreet);
        bdb.put("car",car);
        bdb.put("seats",seats);   
        bdb.put("user",curUser);
        bdb.put("id",no); 
        bdb.put("unique",unique); 
        dbc.insert(bdb);    
        FrmPoolCreateAck f1 =new FrmPoolCreateAck();
        f1.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        cbxCity.setSelectedIndex(-1);
        cbxRegion.setSelectedIndex(-1);
        cbxStreet.setSelectedIndex(-1);
        
        cbxCity1.setSelectedIndex(-1);
        cbxRegion1.setSelectedIndex(-1);
        cbxStreet1.setSelectedIndex(-1);
        
        txtCar.setText("");
        jspSeats.setValue(0);
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        FrmHomepage f1 = new FrmHomepage();
        f1.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPoolCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPoolCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPoolCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPoolCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPoolCreate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cbxCity;
    private javax.swing.JComboBox cbxCity1;
    private javax.swing.JComboBox cbxRegion;
    private javax.swing.JComboBox cbxRegion1;
    private javax.swing.JComboBox cbxStreet;
    private javax.swing.JComboBox cbxStreet1;
    private org.jdesktop.swingx.JXDatePicker jDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private lu.tudor.santec.jtimechooser.JTimeChooser jTime;
    private javax.swing.JSpinner jspSeats;
    private javax.swing.JLabel lblCar;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblRegion1;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblStreet1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUnique;
    private javax.swing.JTextField txtCar;
    private javax.swing.JTextField txtUnique;
    // End of variables declaration//GEN-END:variables
}
