/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;


import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pranav
 */
public class FrmPoolJoin extends javax.swing.JFrame {
static String unique;
    /**
     * Creates new form FrmJoin
     */
    public FrmPoolJoin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jdpDate = new org.jdesktop.swingx.JXDatePicker();
        btnBack = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new org.jdesktop.swingx.JXTable();
        jPanel4 = new javax.swing.JPanel();
        lblStreet1 = new javax.swing.JLabel();
        cbxRegion1 = new javax.swing.JComboBox();
        cbxStreet1 = new javax.swing.JComboBox();
        lblRegion1 = new javax.swing.JLabel();
        lblCity1 = new javax.swing.JLabel();
        cbxCity1 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        lblStreet2 = new javax.swing.JLabel();
        cbxRegion2 = new javax.swing.JComboBox();
        cbxStreet2 = new javax.swing.JComboBox();
        lblRegion2 = new javax.swing.JLabel();
        lblCity2 = new javax.swing.JLabel();
        cbxCity2 = new javax.swing.JComboBox();
        btnClear = new javax.swing.JButton();
        jTimeChooser1 = new lu.tudor.santec.jtimechooser.JTimeChooser();
        btnConfirm = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pooling");

        jTitle.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTitle.setText("Join Car Pooling");

        lblDate.setText("Date:");

        jdpDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdpDateFocusLost(evt);
            }
        });
        jdpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdpDateActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTime.setText("Time:");

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table.setEditable(false);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "From"));

        lblStreet1.setText("Street:");

        cbxRegion1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxRegion1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxRegion1FocusLost(evt);
            }
        });
        cbxRegion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRegion1ActionPerformed(evt);
            }
        });

        cbxStreet1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxStreet1FocusGained(evt);
            }
        });

        lblRegion1.setText("Region:");

        lblCity1.setText("City:");

        cbxCity1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pune" }));
        cbxCity1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxCity1FocusLost(evt);
            }
        });
        cbxCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCity1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblRegion1)
                        .addComponent(lblStreet1))
                    .addComponent(lblCity1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxStreet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxRegion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCity1, lblRegion1, lblStreet1});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxCity1, cbxRegion1, cbxStreet1});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity1)
                    .addComponent(cbxCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion1)
                    .addComponent(cbxRegion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet1)
                    .addComponent(cbxStreet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxCity1, cbxRegion1, cbxStreet1, lblCity1, lblRegion1, lblStreet1});

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "To"));

        lblStreet2.setText("Street:");

        cbxRegion2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxRegion2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxRegion2FocusLost(evt);
            }
        });
        cbxRegion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRegion2ActionPerformed(evt);
            }
        });

        cbxStreet2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxStreet2FocusGained(evt);
            }
        });

        lblRegion2.setText("Region:");

        lblCity2.setText("City:");

        cbxCity2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pune" }));
        cbxCity2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxCity2FocusLost(evt);
            }
        });
        cbxCity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCity2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblRegion2)
                        .addComponent(lblStreet2))
                    .addComponent(lblCity2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxStreet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxRegion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCity2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxCity2, cbxRegion2, cbxStreet2});

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCity2, lblRegion2, lblStreet2});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity2)
                    .addComponent(cbxCity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion2)
                    .addComponent(cbxRegion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet2)
                    .addComponent(cbxStreet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxCity2, cbxRegion2, cbxStreet2, lblCity2, lblRegion2, lblStreet2});

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(233, 233, 233)
                            .addComponent(lblTime)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTimeChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDate)
                            .addGap(18, 18, 18)
                            .addComponent(jdpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTimeChooser1, jdpDate, lblDate, lblTime});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDate)
                        .addComponent(jdpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTime))
                    .addComponent(jTimeChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShow)
                    .addComponent(btnClear)
                    .addComponent(btnBack)
                    .addComponent(btnConfirm)
                    .addComponent(btnHome))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTimeChooser1, jdpDate, lblDate, lblTime});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FrmPoolCar frc=new FrmPoolCar();
        frc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jdpDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdpDateFocusLost
        String date=jdpDate.getDate().toString();
    }//GEN-LAST:event_jdpDateFocusLost

    private void jtcTimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtcTimeFocusLost
       // String time=jtcTime.getFormatedTime();
    }//GEN-LAST:event_jtcTimeFocusLost

    private void cbxRegion1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxRegion1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRegion1FocusGained

    private void cbxRegion1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxRegion1FocusLost
        String selected=cbxRegion1.getSelectedItem().toString();
        Connect c1=new Connect();
        DBCollection dbc=c1.connectStreet(selected);
        BasicDBObject bdb=new BasicDBObject();
        int i=0;
        DBCursor cursor=dbc.find();

        while(cursor.hasNext())
        {
            DBObject obj=cursor.next();
            String street=obj.get("name").toString();
            cbxStreet1.addItem(street);

        }
    }//GEN-LAST:event_cbxRegion1FocusLost

    private void cbxRegion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRegion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRegion1ActionPerformed

    private void cbxStreet1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxStreet1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxStreet1FocusGained

    private void cbxCity1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxCity1FocusLost

        Connect c1=new Connect();
        DBCollection dbc=c1.connectRegion();
        BasicDBObject bdb=new BasicDBObject();
        int i=0;
        DBCursor cursor=dbc.find();

        while(cursor.hasNext())
        {
            DBObject obj=cursor.next();
            String region=obj.get("name").toString();
            cbxRegion1.addItem(region);

        }// TODO add your handling code here:
    }//GEN-LAST:event_cbxCity1FocusLost

    private void cbxCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCity1ActionPerformed

    private void cbxRegion2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxRegion2FocusGained

    }//GEN-LAST:event_cbxRegion2FocusGained

    private void cbxRegion2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxRegion2FocusLost
        String selected1=cbxRegion2.getSelectedItem().toString();
        Connect c1=new Connect();
        DBCollection dbc1=c1.connectStreet(selected1);
        BasicDBObject bdb1=new BasicDBObject();
        int i=0;
        DBCursor cursor1=dbc1.find();
        cbxStreet2.removeAllItems();
        while(cursor1.hasNext())
        {
            DBObject obj=cursor1.next();
            String street=obj.get("name").toString();
            cbxStreet2.addItem(street);

        }
        
        
        Connect c=new Connect();
        DBCollection dbc=c.connectPool();
        BasicDBObject bdb=new BasicDBObject();
        String[] columnNames = {"Id","From City","From Region","From Street","To City","To Region","To Street","Car","Seats","Name"};
        DefaultTableModel dtm = new DefaultTableModel(columnNames,0);
        DBCursor cursor=dbc.find();
            while(cursor.hasNext())
                    {
                    DBObject obj = cursor.next();
                    String fregion1=(String)obj.get("fregion");
                    String selected=cbxRegion2.getSelectedItem().toString();
                    if(fregion1.equals(selected))
                    {
                    String id1=(String)obj.get("id");
                    String fcity=(String)obj.get("fcity");
                    String fregion=(String)obj.get("fregion");
                    String fstreet=(String)obj.get("fstreet");
                    String tcity=(String)obj.get("tcity");
                    String tregion=(String)obj.get("tregion");
                    String tstreet=(String)obj.get("tstreet");
                    String car=(String)obj.get("car");
                    String seats=(String)obj.get("seats");
                    String unique=(String)obj.get("unique");
                    dtm.addRow(new Object[]{id1,fcity,fregion,fstreet,tcity,tregion,tstreet,car,seats,unique});
                    table.setModel(dtm); 
                    }
                }
        
         
        
        

        
        
        
    }//GEN-LAST:event_cbxRegion2FocusLost

    private void cbxRegion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRegion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRegion2ActionPerformed

    private void cbxStreet2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxStreet2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxStreet2FocusGained

    private void cbxCity2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxCity2FocusLost
        // TODO add your handling code here:

        Connect c1=new Connect();
        DBCollection dbc=c1.connectRegion();
        BasicDBObject bdb=new BasicDBObject();
        int i=0;
        DBCursor cursor=dbc.find();

        while(cursor.hasNext())
        {
            DBObject obj=cursor.next();
            String region=obj.get("name").toString();
            cbxRegion2.addItem(region);

        }
    }//GEN-LAST:event_cbxCity2FocusLost

    private void cbxCity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCity2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCity2ActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        Connect c=new Connect();
        DBCollection dbc=c.connectPool();
        BasicDBObject bdb=new BasicDBObject();
        String[] columnNames = {"Id","From City","From Region","From Street","To City","To Region","To Street","Car","Seats","Name"};
        DefaultTableModel dtm = new DefaultTableModel(columnNames,0);
        DBCursor cursor=dbc.find();
            while(cursor.hasNext())
                    {
                    DBObject obj = cursor.next();
                    String fregion1=(String)obj.get("fregion");
                    String selected=cbxRegion2.getSelectedItem().toString();
                    if(fregion1.equals(selected))
                    {
                    String id1=(String)obj.get("id");
                    String fcity=(String)obj.get("fcity");
                    String fregion=(String)obj.get("fregion");
                    String fstreet=(String)obj.get("fstreet");
                    String tcity=(String)obj.get("tcity");
                    String tregion=(String)obj.get("tregion");
                    String tstreet=(String)obj.get("tstreet");
                    String car=(String)obj.get("car");
                    String seats=(String)obj.get("seats");
                    String unique=(String)obj.get("unique");
                    dtm.addRow(new Object[]{id1,fcity,fregion,fstreet,tcity,tregion,tstreet,car,seats,unique});
                    table.setModel(dtm); 
                    }
                }
        
        
        
        
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        cbxCity2.setSelectedIndex(-1);
        cbxRegion2.setSelectedIndex(-1);
        cbxStreet2.setSelectedIndex(-1);
        
        cbxCity1.setSelectedIndex(-1);
        cbxRegion1.setSelectedIndex(-1);
        cbxStreet1.setSelectedIndex(-1);
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void jdpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdpDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdpDateActionPerformed

    public String getUnique()
        {
        String u1;
        u1=unique;
        return u1;
        
        }
    
    
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
     int i =table.getSelectedRow();
       System.out.println("index is"+i);
        String u1   =(String)table.getValueAt(i, 9);
             System.out.println("unique is"+u1);
        FrmPoolJoin.unique=u1;
    System.out.println("done");
        FrmPoolJoinAck f1 =new FrmPoolJoinAck();
        f1.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
        
                    
          

// TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        FrmHomepage f1 = new FrmHomepage();
        f1.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPoolJoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPoolJoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPoolJoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPoolJoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPoolJoin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnShow;
    private javax.swing.JComboBox cbxCity1;
    private javax.swing.JComboBox cbxCity2;
    private javax.swing.JComboBox cbxRegion1;
    private javax.swing.JComboBox cbxRegion2;
    private javax.swing.JComboBox cbxStreet1;
    private javax.swing.JComboBox cbxStreet2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private lu.tudor.santec.jtimechooser.JTimeChooser jTimeChooser1;
    private javax.swing.JLabel jTitle;
    private org.jdesktop.swingx.JXDatePicker jdpDate;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblCity2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblRegion1;
    private javax.swing.JLabel lblRegion2;
    private javax.swing.JLabel lblStreet1;
    private javax.swing.JLabel lblStreet2;
    private javax.swing.JLabel lblTime;
    private org.jdesktop.swingx.JXTable table;
    // End of variables declaration//GEN-END:variables
}
