/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.math.*;

/**
 *
 * @author Abhishek
 */
public class FrmRentCar extends javax.swing.JFrame {
static int no=0;
static int curNo;
public void setRentNo()
    {
    curNo=++no;
    }
public int getRentNo()
    {
    
    return curNo;
    }
    /**
     * Creates new form FrmCarRent
     */
    public FrmRentCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblStreet = new javax.swing.JLabel();
        lblStop = new javax.swing.JLabel();
        cbxCity = new javax.swing.JComboBox();
        cbxRegion = new javax.swing.JComboBox();
        cbxStreet = new javax.swing.JComboBox();
        cbxStop = new javax.swing.JComboBox();
        lblCity = new javax.swing.JLabel();
        lblRegion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblStop1 = new javax.swing.JLabel();
        lblCity1 = new javax.swing.JLabel();
        cbxCity1 = new javax.swing.JComboBox();
        cbxStop1 = new javax.swing.JComboBox();
        lblStreet1 = new javax.swing.JLabel();
        lblRegion1 = new javax.swing.JLabel();
        cbxRegion1 = new javax.swing.JComboBox();
        cbxStreet1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        lblCar = new javax.swing.JLabel();
        cbxDriver = new javax.swing.JComboBox();
        cbxCar = new javax.swing.JComboBox();
        lblDriver = new javax.swing.JLabel();
        lblUnique = new javax.swing.JLabel();
        txtUnique = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        jxTime = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jxDate = new org.jdesktop.swingx.JXDatePicker();
        lblDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Renting");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitle.setText("Car Renting");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "From"));

        lblStreet.setText("Street:");

        lblStop.setText("Stop:");

        cbxCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pune" }));
        cbxCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxCityFocusLost(evt);
            }
        });
        cbxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCityActionPerformed(evt);
            }
        });

        cbxRegion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxRegionFocusLost(evt);
            }
        });
        cbxRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRegionActionPerformed(evt);
            }
        });

        cbxStreet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxStreetFocusLost(evt);
            }
        });

        cbxStop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCity.setText("City:");

        lblRegion.setText("Region:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRegion)
                    .addComponent(lblCity)
                    .addComponent(lblStreet)
                    .addComponent(lblStop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCity, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxCity, cbxRegion, cbxStop, cbxStreet});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCity, lblRegion, lblStop, lblStreet});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(cbxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion)
                    .addComponent(cbxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet)
                    .addComponent(cbxStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStop)
                    .addComponent(cbxStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxCity, lblCity, lblRegion, lblStop, lblStreet});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "To"));

        lblStop1.setText("Stop:");

        lblCity1.setText("City:");

        cbxCity1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pune" }));
        cbxCity1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxCity1FocusLost(evt);
            }
        });
        cbxCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCity1ActionPerformed(evt);
            }
        });

        cbxStop1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblStreet1.setText("Street:");

        lblRegion1.setText("Region:");

        cbxRegion1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxRegion1FocusLost(evt);
            }
        });
        cbxRegion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRegion1ActionPerformed(evt);
            }
        });

        cbxStreet1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxStreet1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRegion1)
                    .addComponent(lblCity1)
                    .addComponent(lblStreet1)
                    .addComponent(lblStop1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxStreet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxRegion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxStop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxCity1, cbxRegion1, cbxStop1, cbxStreet1});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCity1, lblRegion1, lblStop1, lblStreet1});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity1)
                    .addComponent(cbxCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion1)
                    .addComponent(cbxRegion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet1)
                    .addComponent(cbxStreet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStop1)
                    .addComponent(cbxStop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxCity1, lblCity1, lblRegion1, lblStop1, lblStreet1});

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });

        lblCar.setText("Car:");

        cbxDriver.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxDriverFocusGained(evt);
            }
        });

        lblDriver.setText("Driver:");

        lblUnique.setText("Unique Ride Name:");

        lblTime.setText("Time:");

        lblDate.setText("Date:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblUnique)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUnique, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDriver)
                            .addComponent(lblCar))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxDriver, 0, 83, Short.MAX_VALUE)
                            .addComponent(cbxCar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDriver)
                            .addComponent(cbxDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCar)
                            .addComponent(cbxCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDate)
                            .addComponent(jxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTime)
                            .addComponent(jxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnique)
                    .addComponent(txtUnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxCar, cbxDriver, jxDate, jxTime, lblCar, lblDate, lblDriver, lblTime, lblUnique, txtUnique});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnSubmit)
                        .addGap(35, 35, 35)
                        .addComponent(btnClear)
                        .addGap(36, 36, 36)
                        .addComponent(btnHome))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(lblTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnClear)
                    .addComponent(btnHome))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        FrmWelcome f2 = new FrmWelcome();
        String user= f2.getUser();
        this.setRentNo();
        String id;
        id = ""+this.getRentNo();
        id.trim();
        
        String region   = cbxRegion.getSelectedItem().toString();
        String street   = cbxStreet.getSelectedItem().toString();
        String stop     = cbxStop.getSelectedItem().toString();
        String city     = cbxCity.getSelectedItem().toString();
        String region1  = cbxRegion1.getSelectedItem().toString();
        String street1  = cbxStreet1.getSelectedItem().toString();
        String stop1    = cbxStop1.getSelectedItem().toString();
        String city1    = cbxCity1.getSelectedItem().toString();        
        String driver   = cbxDriver.getSelectedItem().toString();
        String car      = cbxCar.getSelectedItem().toString();
        String time     = jxTime.getFormatedTime();
        String date     = jxDate.getDate().toString();
        String unique   = txtUnique.getText();
        /*
        String r1=region;
        String r2=region1;
        
        Connect c2=new Connect();
        DBCollection dbc2=c2.connectRegion();
        BasicDBObject bdb2=new BasicDBObject("name",r1);      
        DBCursor cursor2=dbc2.find();
        DBObject obj2 = cursor2.next();
        String x1 = (String)obj2.get("x");
        String y1 = (String)obj2.get("y");
        
        Connect c3=new Connect();
        DBCollection dbc3=c3.connectRegion();
        BasicDBObject bdb3=new BasicDBObject("name",r2);      
        DBCursor cursor3=dbc3.find();
        DBObject obj3 = cursor3.next();
        String x2 = (String)obj3.get("x");
        String y2 = (String)obj3.get("y");
        
        System.out.println("x1:"+x1);
        System.out.println("y1:"+y1);
        System.out.println("x2:"+x2);
        System.out.println("y2:"+y2);
        
        int a1 = Integer.parseInt(x1);
        int b1 = Integer.parseInt(y1);
        int a2 = Integer.parseInt(x2);
        int b2 = Integer.parseInt(y2);
        
        int cost=(abs(a1-a2)+abs(b1-b2))*40;
        String cost=cost+" rp";
        */
        
        Connect c1      =new Connect();
        DBCollection dbc=c1.connectRent();
        BasicDBObject bdb=new BasicDBObject();
    
        bdb.put("id",id);
        bdb.put("unique",unique);
        bdb.put("user",user);
        
        bdb.put("fcity",city);
        bdb.put("fregion",region);
        bdb.put("fstreet",street);
        bdb.put("fstop",stop);
        bdb.put("tcity",city);
        bdb.put("tregion",region);
        bdb.put("tstreet",street);
        bdb.put("tstop",stop);
        
        bdb.put("driver",driver);
        bdb.put("car",car);
        bdb.put("time",time);
        bdb.put("date",date);
        dbc.insert(bdb);
        
        FrmRentAck f1 = new FrmRentAck();
        f1.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);         
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        cbxCity.setSelectedIndex(-1);
        cbxRegion.setSelectedIndex(-1);
        cbxStreet.setSelectedIndex(-1);
        cbxStop.setSelectedIndex(-1);
        cbxDriver.setSelectedIndex(-1);
        cbxCar.setSelectedIndex(-1);
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        FrmHomepage f1 =new FrmHomepage();
        f1.setVisible(rootPaneCheckingEnabled);
        
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void cbxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCityActionPerformed

    private void cbxCityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxCityFocusLost
        // TODO add your handling code here:
        
            
    Connect c1=new Connect();
    DBCollection dbc=c1.connectRegion();
    BasicDBObject bdb=new BasicDBObject();
    int i=0;
    DBCursor cursor=dbc.find();
     cbxRegion.removeAllItems(); 
    while(cursor.hasNext())
    {
        DBObject obj=cursor.next();
        String region=obj.get("name").toString();
        cbxRegion.addItem(region);
        
    }
    
    }//GEN-LAST:event_cbxCityFocusLost

    private void cbxRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRegionActionPerformed

    private void cbxRegionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxRegionFocusLost
        // TODO add your handling code here:
      String selected=cbxRegion.getSelectedItem().toString();
     Connect c1=new Connect();
    DBCollection dbc=c1.connectStreet(selected);
    BasicDBObject bdb=new BasicDBObject();
    int i=0;
    DBCursor cursor=dbc.find();
     cbxStreet.removeAllItems(); 
    
    
    
    while(cursor.hasNext())
    {
        DBObject obj=cursor.next();
        String street=obj.get("name").toString();
        cbxStreet.addItem(street);
        
    }
    }//GEN-LAST:event_cbxRegionFocusLost

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained
        // TODO add your handling code here:
        // TODO add your handling code here:
            
    }//GEN-LAST:event_jPanel3FocusGained

    private void cbxDriverFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxDriverFocusGained
        // TODO add your handling code here:
  
     
    }//GEN-LAST:event_cbxDriverFocusGained

    private void cbxStreetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxStreetFocusLost
        // TODO add your handling code here:
        
         String selected=cbxRegion.getSelectedItem().toString();
     Connect c1=new Connect();
    DBCollection dbc=c1.connectDriver();
    BasicDBObject bdb=new BasicDBObject();
    DBCursor cursor=dbc.find();
     cbxDriver.removeAllItems(); 
      cbxCar.removeAllItems(); 
    final JPanel j1=new JPanel();
    final JOptionPane j2=new JOptionPane();
        
    while(cursor.hasNext())
    {
        DBObject obj=cursor.next();
        String region1=obj.get("region").toString();
        String dname=obj.get("name").toString();
        String dcar=obj.get("car").toString();
        if(selected.equals(region1))
        { 
        cbxDriver.addItem(dname);
        cbxCar.addItem(dcar);
        }
        /*else
        {
            JOptionPane.showMessageDialog(j1,"Your screwed!","Location not on earth!",JOptionPane.ERROR_MESSAGE);
        }*/
    }
        
    }//GEN-LAST:event_cbxStreetFocusLost

    private void cbxStreet1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxStreet1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxStreet1FocusLost

    private void cbxRegion1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxRegion1FocusLost
        
  String selected=cbxRegion1.getSelectedItem().toString();
     Connect c1=new Connect();
    DBCollection dbc=c1.connectStreet(selected);
    BasicDBObject bdb=new BasicDBObject();
    int i=0;
    DBCursor cursor=dbc.find();   
     cbxStreet1.removeAllItems(); 
    while(cursor.hasNext())
    {
        DBObject obj=cursor.next();
        String street=obj.get("name").toString();
        cbxStreet1.addItem(street);
        
    }
                            


// TODO add your handling code here:
    }//GEN-LAST:event_cbxRegion1FocusLost

    private void cbxRegion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRegion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRegion1ActionPerformed

    private void cbxCity1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxCity1FocusLost
      
            
    Connect c1=new Connect();
    DBCollection dbc=c1.connectRegion();
    BasicDBObject bdb=new BasicDBObject();
    int i=0;
    DBCursor cursor=dbc.find();
    cbxRegion1.removeAllItems();    
    while(cursor.hasNext())
    {
        DBObject obj=cursor.next();
        String region=obj.get("name").toString();
        cbxRegion1.addItem(region);
        
    }        



// TODO add your handling code here:
    }//GEN-LAST:event_cbxCity1FocusLost

    private void cbxCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCity1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRentCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRentCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cbxCar;
    private javax.swing.JComboBox cbxCity;
    private javax.swing.JComboBox cbxCity1;
    private javax.swing.JComboBox cbxDriver;
    private javax.swing.JComboBox cbxRegion;
    private javax.swing.JComboBox cbxRegion1;
    private javax.swing.JComboBox cbxStop;
    private javax.swing.JComboBox cbxStop1;
    private javax.swing.JComboBox cbxStreet;
    private javax.swing.JComboBox cbxStreet1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private org.jdesktop.swingx.JXDatePicker jxDate;
    private lu.tudor.santec.jtimechooser.JTimeChooser jxTime;
    private javax.swing.JLabel lblCar;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDriver;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblRegion1;
    private javax.swing.JLabel lblStop;
    private javax.swing.JLabel lblStop1;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblStreet1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUnique;
    private javax.swing.JTextField txtUnique;
    // End of variables declaration//GEN-END:variables
}
